### ISSUE TITLE
[YOLO] Write-up on YOLO Architecture

### ISSUE THREAD

**Issue by sezan92** [sezan92/computer-vision-course#22]
## Objective

This issue is about the write-up on the YOLO architecture. This is a sub-task of #20 

## Writeup tasks

- [x] Difference with the previous methods
- [x] Architecture Intuition
- [x] Innovations -> Loss function, min-max supression
- [x] Evaluation method

### Definition of Done

When all of the tasks are completed.

**Comment by themurtazanazir** [comment]
@sezan92  In `Innovations -> Loss function, min-max supression`, are you referring "min-max supression" as "Non-Max Supression"?

**Comment by sezan92** [comment]
> @sezan92 In `Innovations -> Loss function, min-max supression`, are you referring "min-max supression" as "Non-Max Supression"?

@themurtazanazir i forgot actual details. i just copied from @AntonisCSt , you can ask him

**Comment by AntonisCSt** [comment]
@themurtazanazir  correct, it should be non-Max Suppression. (it was a typo)

**Comment by themurtazanazir** [comment]
@AntonisCSt thanks for the clarification.
