### ISSUE TITLE
[YOLO] Write-up on using YOLOv8 example

### ISSUE THREAD

**Issue by sezan92** [sezan92/computer-vision-course#24]
## Objective

This issue is about the write-up on usage of YOLOv8 architecture. This is a sub-task of #20 

## Writeup tasks

- [x] Load a data
- [x] How to load YOLOv8
- [x] How to make inference

### Definition of Done

When all of the tasks are completed.

**Comment by AntonisCSt** [comment]
I can take this as well if nobody gets assigned.

**Comment by sezan92** [comment]
@AntonisCSt are you working on it ?

**Comment by AntonisCSt** [comment]
No, I haven't. I can do it next week. (I will be away for a few days)
